# Generated by Django 5.2.1 on 2025-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cinema_movie_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(blank=True),
        ),
    ]
