# Generated by Django 5.2.1 on 2025-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_poster_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_alternative_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
